# Generated by Django 5.0.6 on 2024-07-09 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0002_alter_county_third_town_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaenangtalkPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bae_month', models.DateField(max_length=10, verbose_name='월')),
            ],
        ),
        migrations.CreateModel(
            name='BaenangtalkSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bae_sub_name', models.CharField(max_length=10, verbose_name='주제명')),
            ],
        ),
        migrations.CreateModel(
            name='Baenangtalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bae_title', models.CharField(max_length=100, verbose_name='제목')),
                ('bae_content', models.TextField(verbose_name='내용')),
                ('bae_img', models.ImageField(upload_to='baenangtalk/img', verbose_name='이미지')),
                ('bae_like', models.IntegerField(default=0, verbose_name='좋아요')),
                ('bae_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.county')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baenangtalk.baenangtalkperiod')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baenangtalk.baenangtalksubject')),
            ],
        ),
        migrations.CreateModel(
            name='BaenangtalkComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bae_com_content', models.CharField(max_length=100, verbose_name='내용')),
                ('bae_com_like', models.IntegerField(default=0, verbose_name='좋아요')),
                ('bae_com_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('bae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baenangtalk.baenangtalk')),
            ],
        ),
    ]
