# Generated by Django 5.0.6 on 2024-07-10 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baenangtalk', '0001_initial'),
        ('travel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baenangtalk',
            name='bae_like_by',
            field=models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baenangtalk',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.county', verbose_name='도시'),
        ),
        migrations.AddField(
            model_name='baenangtalk',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baenangtalkcomment',
            name='bae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baenangtalk.baenangtalk'),
        ),
        migrations.AddField(
            model_name='baenangtalkcomment',
            name='bae_com_liked_by',
            field=models.ManyToManyField(related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baenangtalkcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baenangtalk',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baenangtalk.baenangtalkperiod', verbose_name='여행시기'),
        ),
        migrations.AddField(
            model_name='baenangtalk',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baenangtalk.baenangtalksubject', verbose_name='주제'),
        ),
    ]
