# Generated by Django 5.0.6 on 2024-07-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baenangtalk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baenangtalkperiod',
            name='bae_month',
            field=models.DateField(verbose_name='월'),
        ),
    ]
