# Generated by Django 5.0.6 on 2024-07-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baenangtalk', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baenangtalkcomment',
            name='bae_com_content',
            field=models.CharField(max_length=100),
        ),
    ]
