# Generated by Django 5.0.6 on 2024-07-09 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baenangtalk', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baenangtalk',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baenangtalk.baenangtalkperiod', verbose_name='여행시기'),
        ),
        migrations.AlterField(
            model_name='baenangtalk',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baenangtalk.baenangtalksubject', verbose_name='주제'),
        ),
    ]
