# Generated by Django 5.0.6 on 2024-07-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baenangtalk', '0003_alter_baenangtalkcomment_bae_com_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baenangtalkcomment',
            old_name='bae_com_liked_by',
            new_name='bae_com_like_by',
        ),
    ]
