# Generated by Django 5.0.6 on 2024-07-18 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripStyleRecommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_style', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CitySpotRecommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_title', models.CharField(max_length=50)),
                ('rec_address', models.TextField()),
                ('rec_img', models.ImageField(blank=True, null=True, upload_to='planrecommend/img')),
                ('rec_content_id', models.IntegerField(unique=True)),
                ('rec_map_x', models.FloatField(default=0.0)),
                ('rec_map_y', models.FloatField(default=0.0)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec_tour_spots', to='travel.county')),
            ],
        ),
        migrations.CreateModel(
            name='DayPlanRecommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('rec_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planrecommend.cityspotrecommend')),
            ],
        ),
        migrations.CreateModel(
            name='TripRecommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_who', models.CharField(default='혼자', max_length=20)),
                ('rec_start_date', models.DateField()),
                ('rec_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.county')),
            ],
        ),
    ]
