# Generated by Django 5.0.6 on 2024-07-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userinfo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="telnum",
        ),
        migrations.AddField(
            model_name="user",
            name="google_profile",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
