# Generated by Django 5.0.6 on 2024-07-18 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotTravelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_location', models.TextField(verbose_name='지역위치')),
                ('info_weather', models.TextField(verbose_name='지역날씨')),
                ('info_tourist', models.TextField(verbose_name='지역관광지')),
                ('info_cultural', models.TextField(verbose_name='지역문화')),
                ('info_food', models.TextField(verbose_name='지역음식')),
                ('info_traffic', models.TextField(verbose_name='지역교통')),
                ('info_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.county', verbose_name='도시')),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotTravelImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chatbot/%Y/%m', verbose_name='챗봇이미지')),
                ('chatbot_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatbottravelinfo')),
            ],
        ),
    ]
