# Generated by Django 5.0.7 on 2024-07-14 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField()),
                ('number_of_people', models.IntegerField()),
                ('departure_airport', models.CharField(max_length=50)),
                ('arrival_airport', models.CharField(max_length=50)),
                ('departure_time', models.CharField(max_length=50)),
                ('arrival_time', models.CharField(max_length=50)),
                ('flight_number', models.CharField(max_length=50)),
                ('airline_code', models.CharField(max_length=10)),
                ('flight_name', models.CharField(max_length=50)),
                ('free_baggage_allowance', models.IntegerField()),
                ('return_departure_airport', models.CharField(blank=True, max_length=50, null=True)),
                ('return_arrival_airport', models.CharField(blank=True, max_length=50, null=True)),
                ('return_depature_time', models.CharField(blank=True, max_length=50, null=True)),
                ('return_arrival_time', models.CharField(blank=True, max_length=50, null=True)),
                ('return_flight_number', models.CharField(blank=True, max_length=50, null=True)),
                ('return_airline_code', models.CharField(blank=True, max_length=10, null=True)),
                ('return_flight_name', models.CharField(blank=True, max_length=50, null=True)),
                ('return_free_baggage_allowance', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PassengerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(default='대한민국', max_length=50)),
                ('one_way_price', models.IntegerField()),
                ('return_price', models.IntegerField()),
                ('age_category', models.CharField(max_length=20)),
                ('birth_date', models.CharField(max_length=8)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='BookerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.reservation')),
            ],
        ),
    ]
