# Generated by Django 5.0.7 on 2024-07-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='answer_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inquiryimage',
            name='image',
            field=models.ImageField(upload_to='inquiry_images/img'),
        ),
    ]
