# Generated by Django 5.0.6 on 2024-07-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='city_name',
            field=models.CharField(max_length=10, verbose_name='도시그룹'),
        ),
        migrations.AlterField(
            model_name='county',
            name='first_town_name',
            field=models.CharField(max_length=10, verbose_name='첫번째 도시명'),
        ),
        migrations.AlterField(
            model_name='county',
            name='second_town_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='두번쨰 도시명'),
        ),
        migrations.AlterField(
            model_name='county',
            name='third_town_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='세번째 도시명'),
        ),
    ]
