# Generated by Django 5.0.6 on 2024-07-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='third_town_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='세번째 하위도시명'),
        ),
    ]
