# Generated by Django 5.0.3 on 2024-07-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_county_city_name_alter_county_first_town_name_and_more'),
        ('travel', '0002_alter_county_third_town_name'),
    ]

    operations = [
    ]
