# Generated by Django 5.0.6 on 2024-07-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_county_third_town_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='title_image',
            field=models.ImageField(default=1, upload_to='travel_title/%Y/%m', verbose_name='도시메인이미지'),
            preserve_default=False,
        ),
    ]
