# Generated by Django 5.0.6 on 2024-07-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_county_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='city_name',
            field=models.CharField(max_length=15, verbose_name='도시명'),
        ),
    ]
