# Generated by Django 5.0.6 on 2024-07-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_county_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='area_code',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='county',
            name='city_name',
            field=models.CharField(max_length=10, verbose_name='도시명'),
        ),
        migrations.AlterField(
            model_name='county',
            name='first_town_name',
            field=models.CharField(max_length=15, verbose_name='첫번째 하위도시명'),
        ),
    ]
