# Generated by Django 5.0.6 on 2024-07-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_county_area_code_alter_county_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='area_code',
            field=models.IntegerField(null=True),
        ),
    ]
