# Generated by Django 5.0.6 on 2024-07-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_county_area_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='cigungu',
            field=models.IntegerField(null=True),
        ),
    ]
