# Generated by Django 5.0.6 on 2024-07-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_county_cigungu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='county',
            old_name='cigungu',
            new_name='cigungu1',
        ),
        migrations.AddField(
            model_name='county',
            name='cigungu2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='cigungu3',
            field=models.IntegerField(null=True),
        ),
    ]
