# Generated by Django 5.0.6 on 2024-07-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_rename_cigungu_county_cigungu1_county_cigungu2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='cigungu1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='county',
            name='cigungu2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='county',
            name='cigungu3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
