# Generated by Django 5.0.6 on 2024-07-18 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip_style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CitySpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('content_id', models.IntegerField(unique=True)),
                ('map_x', models.FloatField(default=0.0)),
                ('map_y', models.FloatField(default=0.0)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_spots', to='travel.county')),
            ],
        ),
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField()),
                ('day', models.DateField()),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.cityspot')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(default='혼자', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.county')),
            ],
        ),
    ]
