# Generated by Django 5.0.6 on 2024-07-10 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
        ('travel', '0007_county_cigungu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Trip',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('who', models.CharField(default='혼자', max_length=20)),
        #         ('start_date', models.DateField()),
        #         ('end_date', models.DateField()),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.county')),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Trip_style',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('style', models.CharField(max_length=30)),
        #         ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.trip')),
        #     ],
        # ),
    ]
