# Generated by Django 5.0.6 on 2024-07-11 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_trip_trip_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_number', models.IntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.trip')),
            ],
        ),
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField()),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.cityspot')),
                ('trip_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.tripday')),
            ],
        ),
    ]
