# Generated by Django 5.0.6 on 2024-07-11 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_tripday_dayplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayplan',
            name='trip_day',
        ),
        migrations.AddField(
            model_name='dayplan',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plan.trip'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TripDay',
        ),
    ]
