# Generated by Django 5.0.6 on 2024-07-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_dayplan_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityspot',
            name='map_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cityspot',
            name='map_y',
            field=models.FloatField(default=0.0),
        ),
    ]
