# Generated by Django 5.0.3 on 2024-07-10 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_accommodations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AccommodationLike',
        ),
    ]
