# Generated by Django 5.0.3 on 2024-07-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_accommodation_like_delete_accommodationlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='travel_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
