# Generated by Django 5.0.3 on 2024-07-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_alter_review_travel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='guests',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guests_adult',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guests_child',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
