# Generated by Django 5.0.3 on 2024-07-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0004_remove_reservation_guests_reservation_guests_adult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='telnum',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
